apiVersion: apps/v1
kind: Deployment

metadata:
  name: gateway-service
  labels:
    app: gateway-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: gateway-service

  template:
    metadata:
      labels:
        app: gateway-service

    spec:
      containers:
      - name: gateway-service
        image: rchirutkar/gateway-service:v1
        imagePullPolicy: Always

        ports:
        - containerPort: 3003

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "250m"
            memory: "256Mi"

        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 2

        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2